### ISSUE TITLE
Homepage + Iconic incompat

### ISSUE THREAD

**Issue by hdbordercollie** [mirnovov/obsidian-homepage#103]
### Details

When setting a custom icon for the settings menu, Homepage seems to disable pointer events for it and remove the icon that Iconic sets on startup. I'd appreciate if this code could be reviewed to see if there's anything to be done to let Iconic do its job.

I don't even really understand what/why Homepage is doing with the settings icon, and am kinda curious after a fairly excruciatingly thorough debugging session, so that would be appreciated, but absolutely not necessary.

styles.css seems to contain a pointer-events: none !important, and that, I'm even more confused about. I tried removing styles.css and reloading purely for testing, but it seems to be something in the Javascript which is incompatible too.

Cheers

### Steps to reproduce

1. Install Iconic
2. Set a custom icon for the settings cog in the left sidebar (occurred on mobile, not sure about PC)
3. Reload
4. Icon gone, holding to set an icon doesn't do anything

### Debug information

```shell
Callout Integrator
Commander
Default New Tab Page
File Info Panel
Folder Notes
Full Calendar
Homepage
Hover Editor
Iconic
Lazy Plugin Loader
Line Commands
MySnippets
PDF++
Remotely Save
Snippet Commands

Note: All of them are disabled except for Homepage and Iconic, the two needed to reproduce this issue
```

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
How Homepage works (in the default "replace all notes" mode) is that it essentially opens a new workspace with the left and right sidebars the same as before, but the central pane replaced. 

I've tested opening a workspace manually (with Homepage disabled), and Iconic indeed doesn't correctly propagate the settings icon. Since the other icons still work correctly, this is probably best solved on Iconic's end.

There's a bunch of other logic but most of that is fairly inconsequential to what's going on here. The `pointer-events: none !important` is for Homepage's settings pane and won't affect anything when the pane isn't displayed.
