### ISSUE TITLE
Plugin will not turn on!

### ISSUE THREAD

**Issue by dbrianhendrix** [mirnovov/obsidian-homepage#2]
Downloaded plugin, moved it to plugins directory of Obsidian. I can see it under community plugins. However, when I hit the button to turn it on, it says "Failed to load plugin page".

**Comment by mirnovov** [comment]
If installing from source, you need to compile `main.ts` into `main.js` yourself.

**Comment by dbrianhendrix** [comment]
Compile? Or just rename? I didn’t see any instructions at Github to compile.


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist
http://tnnaturalist.org

615.336.4573
***@***.*** ***@***.***>
***@***.*** ***@***.***>
***@***.*** ***@***.***>

**Comment by mirnovov** [comment]
compile.

> I didn’t see any instructions at Github to compile.

now there are instructions ;). I thought it would be kinda obvious, but I guess it isn't. I'd just install it from the plugin browser though.

**Comment by mirnovov** [comment]
To clarify, if you haven't used Node before, you'll have to run `npm i` beforehand to initialise things with Node first.

**Comment by dbrianhendrix** [comment]
I have no idea what “Node” is or what it’s used for. I’ve definitely not ever used “npm i” — is there not a clear site / page for installation instructions?


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist
http://tnnaturalist.org

615.336.4573
***@***.*** ***@***.***>
***@***.*** ***@***.***>
***@***.*** ***@***.***>

**Comment by mirnovov** [comment]
As the installation instructions state, you can also install it using [Obsidian's built-in plugin browser](https://help.obsidian.md/Advanced+topics/Third-party+plugins). I would recommend doing that if you don't have any experience with Node - it would be much easier.

**Comment by dbrianhendrix** [comment]
I have it working now. Previously, this was not available that I could see from the browser search in Obsidian. That’s why I was trying the other method which I’ve done plenty of times with other plugins. Is there somewhere you can point me to that explains the “npm i” process for “compiling”? I’ll be googling as well.

Thanks for your help. You can get technical — I’m a Senior Linux Engineer but I’ve never heard of npm!

D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist
http://tnnaturalist.org

615.336.4573
***@***.*** ***@***.***>
***@***.*** ***@***.***>
***@***.*** ***@***.***>

**Comment by mirnovov** [comment]
That was since it takes a bit for plugins to be approved to show on the browser.

> Is there somewhere you can point me to that explains the “npm i” process for “compiling”? I’ll be googling as well.

Basically, [NPM](https://www.npmjs.com) is a package manager for using JavaScript outside the browser as a scripting language similar to Python. Though it's commonly associated with the Node runtime, it can be used for other JavaScript projects as well, like Obsidian. If you have Homebrew or MacPorts, it can be obtained from there.  

`npm i` downloads all packages for the project and sets up a few system files; NPM is rather ~~poorly designed~~ unusual that it installs all the packages on a per-project basis by default, so this has to be done for each project (ie. each plugin) separately. One of these packages is [TypeScript](https://www.typescriptlang.org), a version of JavaScript by Microsoft that is a strongly typed language. `npm build` uses it in tandem with another package, Rollup, to compile all the plugin's TypeScript files into a single JavaScript file.
