### ISSUE TITLE
Homepage is opened in new tab even if already open elsewhere

### ISSUE THREAD

**Issue by Gewerd-Strauss** [mirnovov/obsidian-homepage#25]
### Summary

If the Homepage is still open (from last time) when the program starts, it still gets opened again in a new tab.

### Steps to reproduce

1. Open the homepage (and additional notes, if you want to)
2. close the vault
3. open it again

### Obsidian info

Opening Method: Keep Open notes (required as I have other notes I have to keep open at all times)
View: Reading View
Installed plugins (there must be a better way of getting all active plugins copied to the clipboard :P)
![grafik](https://user-images.githubusercontent.com/80548781/206857391-65580356-c823-454f-80dd-6b63b4de35df.png)
![grafik](https://user-images.githubusercontent.com/80548781/206857418-8efc4ad7-31ef-4626-bdd0-953ec31e12f2.png)

Testing it in isolation in the sandbox vault was unsuccessful.

### Obsidian version

1.0.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
Unfortunately I can't replicate your issue, even when installing and enabling all the plugins on your list (excluding "Export Setting", which I cannot find).

It's most likely that your issue is unique to certain settings in the complex interplay of plugins you have. As I don't know the exact makeup of your vault, I would recommend testing this by disabling portions of your plugins and reloading until the issue no longer occurs, then narrowing it down. That way, you can discover what plugin is causing this issue and I can investigate further.

> Testing it in isolation in the sandbox vault was unsuccessful.

Unfortunately the sandbox seems to break Homepage, so when I want to test stuff, I just create a new testing vault (usually a copy of either the sandbox or my own vault).

**Comment by mirnovov** [comment]
I've closed this issue due to inactivity, as I can't reproduce it with the current amount of information.

**Comment by mirnovov** [comment]
I've closed this issue due to inactivity, as I can't reproduce it with the current amount of information.
