### ISSUE TITLE
Homepage will close file in right-top corner area after reload window

### ISSUE THREAD

**Issue by quanru** [mirnovov/obsidian-homepage#61]
### Details

![image](https://github.com/mirnovov/obsidian-homepage/assets/11739753/31bc4803-53fe-4660-87c9-1c54b426083b)

### Steps to reproduce

drag a file into right-top corner, and restart obsidian, it will close the file. but it won't be close when disable Homepage plugin

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
This is intentional. You can change the homepage settings to retain other notes that you have open though. Any option that is not "Replace all open notes" should work.
<img width="794" alt="Untitled" src="https://github.com/mirnovov/obsidian-homepage/assets/73574818/22962fb8-d679-45d9-a3b5-57d0e508957d">

If you want it to close all notes in the main pane but keep ones in the right, that is currently not an option.
