### ISSUE TITLE
Opens the homenote with the default text app instead of obsidian

### ISSUE THREAD

**Issue by philippweinmann** [mirnovov/obsidian-homepage#85]
### Details

![image](https://github.com/mirnovov/obsidian-homepage/assets/38894417/e5d8e66b-5893-4caa-b8a3-bf24bbccf8af)

On Pop!_OS.

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by mirnovov** [comment]
This occurs if you already have a file with the homepage name but no extension - see #50. Unfortunately this is a core Obsidian behaviour (the same occurs if you open a link IIRC) so not much I can do about that.

If this issue is occurring without this scenario, lmk and I'm happy to investigate further.

**Comment by philippweinmann** [comment]
Oh okay, I'll check tonight.

Thanks for the plugin btw! It is very useful!!
